version: '{build}'
os: Visual Studio 2017
branches:
  only:
  - master
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_commits:
  files:
    - LICENSE
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/huoshan12345/api/v2/package
  api_key:
    secure: pVZ8cfaAD/kj48+EAc3tRs6ozE6O92CIWnwXVsSWfoYi9/j5w89K5BO5KYX17I1p
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    branch: master
